server:
  port: 8888
spring:
    datasource:
        name: db
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql:replication://localhost:3306,localhost:3306/seckill?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: root
        #连接池的配置信息
        driver-class-name: com.mysql.jdbc.ReplicationDriver
        minIdle: 5
        maxActive: 100
        initialSize: 10
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 50
        removeAbandoned: true
        filters: stat # ,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
        druidLoginName: admin # 登录druid的账号
        druidPassword: 123456 # 登录druid的密码
    redis: #redis基础配置
      host: 127.0.0.1
      port: 6370
      timeout: 1000
      jedis:
        pool:
          max-idle: 500 # 连接池中的最大空闲连接，默认值也是8。
          min-idle: 50 #连接池中的最小空闲连接，默认值也是0。
          max-active: 2000 # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
          max-wait: 1000 # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException

mybatis:
     mapperLocations: classpath:mapper/*.xml
     typeAliasesPackage: com.myself.seckill.entity
     mapperScanPackage: com.myself.seckill.dao
     configLocation: classpath:mybatis.xml
